# Generated by Django 5.2 on 2025-06-02 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newspaper", "0008_newsletter"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["name"],
                "verbose_name": "category",
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.AddField(
            model_name="post",
            name="is_breaking_news",
            field=models.BooleanField(default=False),
        ),
    ]
